// <auto-generated />
using System;
using SchoolErpSMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SchoolErpSMS.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20251124003546_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolErpSMS.Entities.AcademicYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("AcademicYears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsClosed = false,
                            Name = "2025",
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.BabyClassSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BabyClassSkills");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.BabyClassSkillAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssessedBy")
                        .HasColumnType("int");

                    b.Property<int>("SkillItemId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssessedBy");

                    b.HasIndex("SkillItemId");

                    b.HasIndex("StudentId");

                    b.ToTable("BabyClassSkillAssessments");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.BabyClassSkillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.ToTable("BabyClassSkillItems");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.ExamScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("CommentsUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CommentsUpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("CommentsUpdatedByTeacherId")
                        .HasColumnType("int");

                    b.Property<int>("ExamTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAbsent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecordedBy")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentsUpdatedByTeacherId");

                    b.HasIndex("ExamTypeId");

                    b.HasIndex("GradeId");

                    b.HasIndex("RecordedBy");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId", "ExamTypeId", "AcademicYear", "Term")
                        .IsUnique();

                    b.ToTable("ExamScores");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.ExamType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExamTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "First test of the term",
                            IsActive = true,
                            Name = "Test-One",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Second-test examination",
                            IsActive = true,
                            Name = "Test-Two",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "End of term examination",
                            IsActive = true,
                            Name = "End-of-Term",
                            Order = 3
                        });
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.Grade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HomeroomTeacherId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.Property<string>("Stream")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HomeroomTeacherId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Level = 11,
                            Name = "Form 1",
                            Section = 4,
                            Stream = "W"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Level = 11,
                            Name = "Form 1",
                            Section = 4,
                            Stream = "X"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Level = 11,
                            Name = "Form 1",
                            Section = 4,
                            Stream = "Y"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Level = 12,
                            Name = "Grade 10",
                            Section = 5,
                            Stream = "V"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Level = 12,
                            Name = "Grade 10",
                            Section = 5,
                            Stream = "W"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Level = 12,
                            Name = "Grade 10",
                            Section = 5,
                            Stream = "X"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Level = 12,
                            Name = "Grade 10",
                            Section = 5,
                            Stream = "Y"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Level = 13,
                            Name = "Grade 11",
                            Section = 5,
                            Stream = "V"
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Level = 13,
                            Name = "Grade 11",
                            Section = 5,
                            Stream = "W"
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Level = 13,
                            Name = "Grade 11",
                            Section = 5,
                            Stream = "X"
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Level = 13,
                            Name = "Grade 11",
                            Section = 5,
                            Stream = "Y"
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Level = 14,
                            Name = "Grade 12",
                            Section = 5,
                            Stream = "V"
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Level = 14,
                            Name = "Grade 12",
                            Section = 5,
                            Stream = "W"
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Level = 14,
                            Name = "Grade 12",
                            Section = 5,
                            Stream = "X"
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Level = 14,
                            Name = "Grade 12",
                            Section = 5,
                            Stream = "Y"
                        });
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.GradeSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("GradeId", "SubjectId")
                        .IsUnique();

                    b.ToTable("GradeSubjects");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.ReportCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("GeneralComment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("GeneralCommentUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GeneralCommentUpdatedBy")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralCommentUpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedBy")
                        .HasColumnType("int");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GeneralCommentUpdatedByUserId");

                    b.HasIndex("GeneratedBy");

                    b.HasIndex("GradeId");

                    b.HasIndex("StudentId");

                    b.ToTable("ReportCards");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.SmsLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MessageType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProviderResponse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SentByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("Term")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYear");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("SentAt");

                    b.HasIndex("SentByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.ToTable("SmsLogs");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ArchiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<string>("GuardianName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuardianPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.StudentOptionalSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId")
                        .IsUnique();

                    b.ToTable("StudentOptionalSubjects");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.StudentSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DroppedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EnrolledDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("StudentId", "SubjectId")
                        .IsUnique();

                    b.ToTable("StudentSubjects");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.StudentTechnologyTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SelectedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentTechnologyTracks");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "MATH",
                            IsActive = true,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ENG",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            Id = 3,
                            Code = "SCI",
                            IsActive = true,
                            Name = "Integrated Science"
                        },
                        new
                        {
                            Id = 4,
                            Code = "SS",
                            IsActive = true,
                            Name = "Social Studies"
                        },
                        new
                        {
                            Id = 5,
                            Code = "FR",
                            IsActive = true,
                            Name = "French"
                        },
                        new
                        {
                            Id = 6,
                            Code = "ICT",
                            IsActive = true,
                            Name = "ICT"
                        },
                        new
                        {
                            Id = 7,
                            Code = "PE",
                            IsActive = true,
                            Name = "Physical Education"
                        },
                        new
                        {
                            Id = 8,
                            Code = "REA",
                            IsActive = true,
                            Name = "Reading"
                        },
                        new
                        {
                            Id = 11,
                            Code = "CTS",
                            IsActive = true,
                            Name = "CTS"
                        },
                        new
                        {
                            Id = 25,
                            Code = "MDE",
                            IsActive = true,
                            Name = "MDE"
                        },
                        new
                        {
                            Id = 35,
                            Code = "CINY",
                            IsActive = true,
                            Name = "Cinyanja"
                        },
                        new
                        {
                            Id = 36,
                            Code = "SCIE",
                            IsActive = true,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 33,
                            Code = "CS",
                            IsActive = true,
                            Name = "Computer Studies"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BIO",
                            IsActive = true,
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 9,
                            Code = "SP1",
                            IsActive = true,
                            Name = "SP1"
                        },
                        new
                        {
                            Id = 10,
                            Code = "SP2",
                            IsActive = true,
                            Name = "SP2"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AGRI",
                            IsActive = true,
                            Name = "Agriculture Science"
                        },
                        new
                        {
                            Id = 13,
                            Code = "HIST",
                            IsActive = true,
                            Name = "History"
                        },
                        new
                        {
                            Id = 14,
                            Code = "GEO",
                            IsActive = true,
                            Name = "Geography"
                        },
                        new
                        {
                            Id = 15,
                            Code = "REL",
                            IsActive = true,
                            Name = "Religious Studies"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BUS",
                            IsActive = true,
                            Name = "Business Studies"
                        },
                        new
                        {
                            Id = 17,
                            Code = "ACC",
                            IsActive = true,
                            Name = "Accounts"
                        },
                        new
                        {
                            Id = 18,
                            Code = "ECO",
                            IsActive = true,
                            Name = "Economics"
                        },
                        new
                        {
                            Id = 19,
                            Code = "PHY",
                            IsActive = true,
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 20,
                            Code = "CHEM",
                            IsActive = true,
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 22,
                            Code = "LIT",
                            IsActive = true,
                            Name = "Literature in English"
                        },
                        new
                        {
                            Id = 23,
                            Code = "CIV",
                            IsActive = true,
                            Name = "Civic Education"
                        },
                        new
                        {
                            Id = 24,
                            Code = "MUS",
                            IsActive = true,
                            Name = "Music"
                        },
                        new
                        {
                            Id = 26,
                            Code = "HE",
                            IsActive = true,
                            Name = "Home Economics"
                        },
                        new
                        {
                            Id = 34,
                            Code = "COMSCI",
                            IsActive = true,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 37,
                            Code = "COMMER",
                            IsActive = true,
                            Name = "Commerce"
                        },
                        new
                        {
                            Id = 39,
                            Code = "ART",
                            IsActive = true,
                            Name = "Art & Design"
                        },
                        new
                        {
                            Id = 40,
                            Code = "F&N",
                            IsActive = true,
                            Name = "Food and Nutrition"
                        },
                        new
                        {
                            Id = 46,
                            Code = "D&T",
                            IsActive = true,
                            Name = "Design and Technology"
                        },
                        new
                        {
                            Id = 47,
                            Code = "F&F",
                            IsActive = true,
                            Name = "Fashion and Fabrics"
                        },
                        new
                        {
                            Id = 48,
                            Code = "HOSP",
                            IsActive = true,
                            Name = "Hospitality Management"
                        },
                        new
                        {
                            Id = 49,
                            Code = "T&T",
                            IsActive = true,
                            Name = "Travel and Tourism"
                        },
                        new
                        {
                            Id = 50,
                            Code = "FL",
                            IsActive = true,
                            Name = "Foreign Language"
                        },
                        new
                        {
                            Id = 51,
                            Code = "ZL",
                            IsActive = true,
                            Name = "Zambian Language"
                        },
                        new
                        {
                            Id = 52,
                            Code = "POA",
                            IsActive = true,
                            Name = "Principles of Accounts"
                        },
                        new
                        {
                            Id = 53,
                            Code = "LITZL",
                            IsActive = true,
                            Name = "Literature in Zambian Language"
                        },
                        new
                        {
                            Id = 41,
                            Code = "LANG",
                            IsActive = true,
                            Name = "Language"
                        },
                        new
                        {
                            Id = 42,
                            Code = "PREMATH",
                            IsActive = true,
                            Name = "Pre-Math"
                        },
                        new
                        {
                            Id = 43,
                            Code = "TOPIC",
                            IsActive = true,
                            Name = "Topic"
                        },
                        new
                        {
                            Id = 44,
                            Code = "ELCCTS",
                            IsActive = true,
                            Name = "Creative And Technology Studies (CTS)"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CREAT",
                            IsActive = true,
                            Name = "Creative Activities"
                        },
                        new
                        {
                            Id = 27,
                            Code = "COMMSK",
                            IsActive = true,
                            Name = "Communication Skills"
                        },
                        new
                        {
                            Id = 28,
                            Code = "FM",
                            IsActive = true,
                            Name = "Fine-motor Skills"
                        },
                        new
                        {
                            Id = 29,
                            Code = "GMS",
                            IsActive = true,
                            Name = "Gross-motor Skills"
                        },
                        new
                        {
                            Id = 30,
                            Code = "SESK",
                            IsActive = true,
                            Name = "Social-emotional Skills"
                        },
                        new
                        {
                            Id = 31,
                            Code = "COLSS",
                            IsActive = true,
                            Name = "Colors & Shapes"
                        },
                        new
                        {
                            Id = 32,
                            Code = "NUMB",
                            IsActive = true,
                            Name = "Numbers"
                        });
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.TeacherSubjectAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GradeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSubjectAssignments");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@scherp.sch.edu",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$I0Q7cC9y7.NTwp3hWV3QnOfYsVkRZi1ZsRa1IVGck5VIriBdoip.O",
                            Role = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.BabyClassSkillAssessment", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.User", "AssessedByNavigation")
                        .WithMany()
                        .HasForeignKey("AssessedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.BabyClassSkillItem", "SkillItem")
                        .WithMany("SkillAssessments")
                        .HasForeignKey("SkillItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssessedByNavigation");

                    b.Navigation("SkillItem");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.BabyClassSkillItem", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.BabyClassSkill", "Skill")
                        .WithMany("SkillItems")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.ExamScore", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.User", "CommentsUpdatedByTeacher")
                        .WithMany()
                        .HasForeignKey("CommentsUpdatedByTeacherId");

                    b.HasOne("SchoolErpSMS.Entities.ExamType", "ExamType")
                        .WithMany("ExamScores")
                        .HasForeignKey("ExamTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.User", "RecordedByTeacher")
                        .WithMany()
                        .HasForeignKey("RecordedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.Student", "Student")
                        .WithMany("ExamScores")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.Subject", "Subject")
                        .WithMany("ExamScores")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CommentsUpdatedByTeacher");

                    b.Navigation("ExamType");

                    b.Navigation("Grade");

                    b.Navigation("RecordedByTeacher");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.Grade", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.User", "HomeroomTeacher")
                        .WithMany("HomeroomGrades")
                        .HasForeignKey("HomeroomTeacherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("HomeroomTeacher");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.GradeSubject", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.Grade", "Grade")
                        .WithMany("GradeSubjects")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.Subject", "Subject")
                        .WithMany("GradeSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.ReportCard", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.User", "GeneralCommentUpdatedByUser")
                        .WithMany()
                        .HasForeignKey("GeneralCommentUpdatedByUserId");

                    b.HasOne("SchoolErpSMS.Entities.User", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneralCommentUpdatedByUser");

                    b.Navigation("GeneratedByUser");

                    b.Navigation("Grade");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.SmsLog", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.AcademicYear", "AcademicYearNavigation")
                        .WithMany()
                        .HasForeignKey("AcademicYear")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolErpSMS.Entities.User", "SentByUser")
                        .WithMany()
                        .HasForeignKey("SentByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SchoolErpSMS.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AcademicYearNavigation");

                    b.Navigation("SentByUser");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.Student", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.Grade", "Grade")
                        .WithMany("Students")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.StudentOptionalSubject", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.Student", "Student")
                        .WithMany("OptionalSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.Subject", "Subject")
                        .WithMany("StudentOptionalSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.StudentSubject", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.Student", "Student")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.Subject", "Subject")
                        .WithMany("StudentSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.StudentTechnologyTrack", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.TeacherSubjectAssignment", b =>
                {
                    b.HasOne("SchoolErpSMS.Entities.Grade", "Grade")
                        .WithMany()
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.Subject", "Subject")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolErpSMS.Entities.User", "Teacher")
                        .WithMany("TeacherAssignments")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.BabyClassSkill", b =>
                {
                    b.Navigation("SkillItems");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.BabyClassSkillItem", b =>
                {
                    b.Navigation("SkillAssessments");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.ExamType", b =>
                {
                    b.Navigation("ExamScores");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.Grade", b =>
                {
                    b.Navigation("GradeSubjects");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.Student", b =>
                {
                    b.Navigation("ExamScores");

                    b.Navigation("OptionalSubjects");

                    b.Navigation("StudentSubjects");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.Subject", b =>
                {
                    b.Navigation("ExamScores");

                    b.Navigation("GradeSubjects");

                    b.Navigation("StudentOptionalSubjects");

                    b.Navigation("StudentSubjects");

                    b.Navigation("TeacherAssignments");
                });

            modelBuilder.Entity("SchoolErpSMS.Entities.User", b =>
                {
                    b.Navigation("HomeroomGrades");

                    b.Navigation("TeacherAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
